[tests-only]Add webUI tests for impersonate
owncloud/impersonate pull request #220
Opened 2022-10-25 10:40 UTC by SwikritiT

This PR adds the WebUI tests for impersonation.
Part of:  https://github.com/owncloud/impersonate/issues/215

2022-10-31 05:42 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>webUIImpersonate-master-chrome-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/impersonate/1693/11
<!-- id: pr-220 -->

2022-11-02 07:04 UTC, SwikritiT commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		\usleep(200000);
This amount of sleep is required for the test to pass in firefox, we need to decide if it is a `necessity` for tests to run in firefox or if they can be skipped there.

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/UserImpersonatePage.php
> + * @author Paurakh Sharma Humagain <paurakh@jankaritech.com>
```suggestion
 * @author Paurakh Sharma Humagain <paurakh@jankaritech.com>
```
I was thinking you're swikriti ;)

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +			__METHOD__ . " could not find element with id $this->impersonateNotificationXpath"
```suggestion
			__METHOD__ . " could not find element with the xpath '$this->impersonateNotificationXpath'"
```

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +			__METHOD__ . " could not find element with id $this->userXpath"
```suggestion
			__METHOD__ . " could not find element with xpath '$this->userXpath'"
```

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		$userTr= $this->findUserInTable($user);
```suggestion
		$userFromTable= $this->findUserInTable($user);
```
or any nice words...

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +			__METHOD__ . " could not find element with id $this->impersonateXpath"
```suggestion
			__METHOD__ . " could not find element with xpath '$this->impersonateXpath'"
```

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUIImpersonateContext.php
> +		);
```suggestion
                $actualUsername = $this->userImpersonatePage->userShouldBeInTheirPage()
		Assert::assertEquals(
			$username,
			$actualUsername,
			__METHOD__
			. " Username was expected to be '$username', but got '"
			. $actualUsername
			. "' instead"
		);
```

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/WebUIImpersonateContext.php
> +		);
reuse that username grabbing part.

2022-11-02 08:40 UTC, kiranparajuli589 commented on tests/acceptance/features/bootstrap/ImpersonateAppContext.php
> +	 * @Given /^the administrator has created following users with group and role:$/
role is optional here :thinking: maybe
```suggestion
	 * @Given /^the administrator has created following users with settings:$/
```

2022-11-02 10:55 UTC, SagarGi commented on tests/acceptance/features/bootstrap/WebUIImpersonateContext.php
> +			$this->userImpersonatePage->getImpersonationNotificationText(),
make be put this in a variable above and use instead of directly calling?

2022-11-02 10:55 UTC, SagarGi commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +	 * @return string
```suggestion
	 *
	 * @return string
```

2022-11-03 03:46 UTC, SwikritiT commented on tests/acceptance/features/lib/UserImpersonatePage.php
> + * @author Paurakh Sharma Humagain <paurakh@jankaritech.com>
I was trying to impersonate Paurakh dai ;)

2022-11-03 05:53 UTC, kiranparajuli589 reviewed
looks good :+1:

2022-11-03 09:59 UTC, saw-jan commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		\usleep(200000);
thoughts?
```suggestion
                // wait for 200 milliseconds
		\usleep(200 * 1000);
```

2022-11-03 10:02 UTC, saw-jan commented on tests/acceptance/features/bootstrap/WebUIImpersonateContext.php
> +		$this->owncloudPage=$owncloudPage;
```suggestion
		$this->userImpersonatePage = $userImpersonatePage;
		$this->owncloudPage = $owncloudPage;
```

2022-11-03 10:04 UTC, saw-jan commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		$userFromTable= $this->findUserInTable($user);
```suggestion
		$userFromTable = $this->findUserInTable($user);
```

2022-11-03 10:04 UTC, saw-jan commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		$notificationElement= $this->find('xpath', $this->impersonateNotificationXpath);
```suggestion
		$notificationElement = $this->find('xpath', $this->impersonateNotificationXpath);
```

2022-11-03 11:17 UTC, SwikritiT commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    And the user has logged out of the webUI
It might I'll try with sending a folder creation req

2022-11-03 11:30 UTC, kiranparajuli589 commented on Makefile
> +	composer bin phpstan install --no-progress
the existing one was okay here imo, others are using the variables too.

2022-11-04 04:43 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-11-04 06:01 UTC, saw-jan commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    #impersonation only works after the user has logged in or sent some api req
Could this comment be moved to the top level? Describing something like `impersonation works only after the user being impersonated has sent some requests`

2022-11-04 08:31 UTC, SwikritiT commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    #impersonation only works after the user has logged in or sent some api req
You mean like at the top of the scenario or the feature file itself?

2022-11-04 09:17 UTC, saw-jan commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    #impersonation only works after the user has logged in or sent some api req
Yup! what would you say?

2022-11-04 11:38 UTC, SwikritiT commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    #impersonation only works after the user has logged in or sent some api req
added comment to the top

2022-11-07 03:33 UTC, saw-jan commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +#impersonation only works after the user has logged in or sent some api req
Could be more noticeable
```suggestion
# NOTE: Impersonation only works after the user (to be impersonated) has logged in or sent some API requests
```

2022-11-09 03:54 UTC, SagarGi reviewed
others LGTM :+1:

2022-11-09 03:54 UTC, SagarGi commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    And user "Alice" has created folder "test-folder"
the `test-folder` seems to be created and there is no use of it. is this the API request for the impersonation to work?

2022-11-09 04:01 UTC, SwikritiT commented on tests/acceptance/features/webUIImpersonate/impersonate.feature
> +    And user "Alice" has created folder "test-folder"
Yes it's for the impersonation to work

2022-11-09 05:27 UTC, saw-jan reviewed
LGTM :+1:

2022-11-09 05:58 UTC, individual-it requested changes
Looks great, good job. I just have one question/suggestion.

2022-11-09 05:58 UTC, individual-it commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		\usleep(300 * 1000);
can we instead loop the `find` till there is no exception anymore?

2022-11-10 10:58 UTC, SwikritiT commented on tests/acceptance/features/lib/UserImpersonatePage.php
> +		\usleep(300 * 1000);
Done

2022-11-14 08:23 UTC, individual-it approved these changes

2022-11-14 08:23 UTC, merged